#!/bin/sh
#
# Updates an existing Claude Code installation for current user.
#
# This is a variant assuming regular setup, corresponding to the setup
# created by the official installation script https://claude.ai/install.sh,
# relying on the 'claude install' command. The built-in updater can then be
# used, either the auto-updater or by manually running the 'claude update'
# command, which this script does. In this setup, multiple versions of the
# executable are kept in directory ~/.local/share/claude/versions and
# ~/.local/bin/claude is maintained as a symbolic link to the current (latest)
# of them. Note that if the existing is standalone setup, running this script
# (or 'claude update') will migrate it to a regular setup.
#
# By default Claude checks for updates on startup and periodically while
# running, and it will download and install in the background, and they take
# effect the next time Claude Code is started. These automatic updates can be
# disabled. Manual updates can be triggered with command 'claude update'. It
# will look up latest version, compare with existing version, and update if
# newer. The main (only) additional thing this script provides, is an update
# check. It looks up latest version and compares with existing version, but
# then it asks user if it should proceed with the update. This makes it
# possible to check for new versions, without necessarily update immediately!
# If user decides to perform the update, then this is simply done by running
# 'claude update' command - which of course then will do its own lookup, and
# also repeat information on output that this script already have logged: When
# no update it reports:
#   Current version: 2.1.90
#   Checking for updates to latest version...
#   Claude Code is up to date (2.1.90)
# When there is an update it reports:
#   Current version: 2.1.89
#   Checking for updates to latest version...
#   Successfully updated from 2.1.89 to version 2.1.90
#
# This script can be run with argument --dry-run or -n to only check versions,
# but not update, and not prompt user to ask if an update should be preformed.
# For completeness with other scripts this script can be executed with argument
# --noconfirm to run non-interactively proceeding without prompting user. This
# means if there is an update available, it will be installed.
#
# SEE ALSO:
#   https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/bootstrap.sh
#

# Verify not running as root, since this installs Claude Code for the current user.
if [ ${EUID:-$(id -u)} -eq 0 ]; then
    echo 'Please do not run this script as root' >&2
    exit 1
fi

echo "Finding existing version..."
existing_path=$(command -v claude 2> /dev/null)
if [ -z "$existing_path" ]; then
    echo "The command 'claude' is not available in this shell session" >&2
    exit 1
fi
if [ "$existing_path" != "${HOME}/.local/bin/claude" ]; then
    echo "The command 'claude' is at path ${existing_path} instead of the expected '~/.local/bin/claude'" >&2
    exit 1
fi
if [ ! -L "${HOME}/.local/bin/claude" ]; then
    echo "The path '~/.local/bin/claude' is not a symbolic link so this looks like a standalone and not regular setup" >&2
    exit 1
fi
existing_version=$(claude --version | sed 's/^\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\) (Claude Code)$/\1/')
if [ -z "$existing_version" ]; then
    echo "Failed to find existing version from output of command 'claude'" >&2
    exit 1
fi
echo "Existing version is ${existing_version}"

echo "Finding latest version..."
base_url=https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases
latest_version=$(curl --fail --silent --show-error --location "${base_url}/latest")
if [ -z "$latest_version" ]; then
    echo "Failed to fetch latest version" >&2
    exit 1
fi
echo "Latest version is ${latest_version}"
manifest=$(curl --fail --silent --show-error --location "${base_url}/${latest_version}/manifest.json" | tr -d '\n\r\t' | sed 's/ \+/ /g')
if [ -z "$manifest" ]; then
    echo "Failed to fetch version manifest" >&2
    exit 1
fi
manifest_version=$(echo "$manifest" | sed 's/.*"version": "\([^"]*\)".*/\1/')
if [ "$latest_version" != "$manifest_version" ]; then
    echo "Version mismatch, expected ${latest_version} but was ${manifest_version}" >&2
    exit 1
fi
manifest_date=$(echo "$manifest" | sed 's/.*"buildDate": "\([^"]*\)".*/\1/')
if [ -n "$manifest_date" ]; then
    echo "Latest version was published $(date --date="${manifest_date}" 2> /dev/null) (${manifest_date})"
else
    echo "Unable to find published date"
fi
echo "Comparing version..."
if [ "$latest_version" != "$existing_version" ]; then
    echo "NOTICE: A new version ${latest_version} is available"
    if [ "$1" = '--dry-run' ] || [ "$1" = '-n' ]; then
        exit 2 # Note: Exit code 2 here to indicate not an error but an update was available!
    fi
    if [ "$1" != '--noconfirm' ]; then
        read -p "Run 'claude update' to update from version ${existing_version} now? [Y/n] " choice
        case "$choice" in
        ""|y|Y );;
        * ) echo "Skipped" >&2; exit 2;; # Note: Exit code 2 here to indicate not an error but an update was available!
        esac
    fi
    echo "Running Claude Code update command..."
    if ! claude update; then
        echo "Failed!" >&2
        exit 1
    fi
    new_version=$(claude --version | sed 's/^\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\) (Claude Code)$/\1/')
    if [ -z "$new_version" ]; then
        echo "Failed to find new version from output of command 'claude'" >&2
        exit 1
    fi
    if [ "$new_version" != "$latest_version" ]; then
        echo "WARNING: The output of command 'claude' indicates this is version ${new_version} and not ${latest_version}"
    else
        echo "Version is now ${new_version}"
    fi
else
    echo "Existing version ${existing_version} is up to date"
fi
