#!/bin/sh
#
# Updates an existing Claude Code installation for current user.
#
# This is a variant assuming the more standalone setup than the regular
# setup. When the official Claude Code install command was not used, the
# application executable is directly installed as ~/.local/bin/claude,
# and we update it by downloading and replacing it with the latest version.
# In the regular setup this is simply a symlink to one of several versions
# of the executable installed into directory ~/.local/share/claude. Note
# that if the built-in update functionality is used, either the auto-updater
# or the 'claude update' command, it will migrate to the regular setup!
# So to keep this standalone setup, update must be done manually by downloading
# and replacing the binary, like this script does! To migrate back to
# standalone setup when default paths are used, the following command should
# work:
#   mv "$(readlink ~/.local/bin/claude)" ~/.local/bin/claude && rm -rf ~/.local/share/claude/versions
#
# This script can be run with argument --dry-run or -n to only check versions,
# but not update, and not prompt user to ask if an update should be performed.
# For completeness with other scripts this script can be executed with argument
# --noconfirm to run non-interactively proceeding without prompting user. This
# means if there is an update available, it will be installed.
#
# SEE ALSO:
#   https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/bootstrap.sh
#

# If we could always assume that the distro is always set up with a non-root
# default user, then we could verify we are not running as root, since this
# considers a local Claude Code installation for the current user only!
#if [ ${EUID:-$(id -u)} -eq 0 ]; then
#    echo 'Please do not run this script as root' >&2
#    exit 1
#fi

# Resolve XDG conventional user binary directory.
# This is where the Claude executable is installed by default, and here we
# assume it was not manually installed elsewhere.
bin_dir="${HOME}/.local/bin"

# Resolve Claude-specific configuration directory.
# It is ~/.claude by default, and can be overridden by variable
# CLAUDE_CONFIG_DIR, but Claude does not consider XDG_CONFIG_HOME.
config_dir="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"

echo "Finding existing version..."
existing_path=$(command -v claude 2> /dev/null)
if [ -z "$existing_path" ]; then
    echo "The command 'claude' is not available in this shell session" >&2
    exit 1
fi
if [ "$existing_path" != "${bin_dir}/claude" ]; then
    echo "The command 'claude' is at path ${existing_path} instead of the expected '${bin_dir}/claude'" >&2
    exit 1
fi
if [ -L "${bin_dir}/claude" ]; then
    echo "The path '${bin_dir}/claude' is a symbolic link so this looks like a regular and not standalone setup" >&2
    exit 1
fi
existing_version=$(claude --version | sed 's/^\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\) (Claude Code)$/\1/')
if [ -z "$existing_version" ]; then
    echo "Failed to find existing version from output of command 'claude'" >&2
    exit 1
fi
echo "Existing version is ${existing_version}"

echo "Finding latest version..."
base_url=https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases
latest_version=$(curl --fail --silent --show-error --location "${base_url}/latest")
if [ -z "$latest_version" ]; then
    echo "Failed to fetch latest version" >&2
    exit 1
fi
echo "Latest version is ${latest_version}"
manifest=$(curl --fail --silent --show-error --location "${base_url}/${latest_version}/manifest.json" | tr -d '\n\r\t' | sed 's/ \+/ /g')
if [ -z "$manifest" ]; then
    echo "Failed to fetch version manifest" >&2
    exit 1
fi
manifest_version=$(echo "$manifest" | sed 's/.*"version": "\([^"]*\)".*/\1/')
if [ "$latest_version" != "$manifest_version" ]; then
    echo "Version mismatch, expected ${latest_version} but was ${manifest_version}" >&2
    exit 1
fi
manifest_date=$(echo "$manifest" | sed 's/.*"buildDate": "\([^"]*\)".*/\1/')
if [ -n "$manifest_date" ]; then
    echo "Latest version was published $(date --date="${manifest_date}" 2> /dev/null) (${manifest_date})"
else
    echo "Unable to find published date"
fi
echo "Comparing version..."
if [ "$latest_version" != "$existing_version" ]; then
    echo "NOTICE: A new version ${latest_version} is available"
    if [ "$1" = '--dry-run' ] || [ "$1" = '-n' ]; then
        exit 2 # Note: Exit code 2 here to indicate not an error but an update was available!
    fi
    if [ "$1" != '--noconfirm' ]; then
        read -p "Download version ${latest_version} and replace existing version ${existing_version} now? [Y/n] " choice
        case "$choice" in
        ""|y|Y );;
        * ) echo "Skipped" >&2; exit 2;; # Note: Exit code 2 here to indicate not an error but an update was available!
        esac
    fi
    expected_size=$(echo "$manifest" | sed 's/.*"linux-x64": {[^}]*"size": \([0-9]*\).*/\1/')
    if [ -z "$expected_size" ]; then
        echo "Failed to fetch expected size from version manifest" >&2
        exit 1
    fi
    expected_checksum=$(echo "$manifest" | sed 's/.*"linux-x64": {[^}]*"checksum": "\([^"]*\)".*/\1/')
    if [ -z "$expected_checksum" ]; then
        echo "Failed to fetch expected checksum from version manifest" >&2
        exit 1
    fi
    echo "Downloading..."
    if ! curl --fail --silent --show-error --location "${base_url}/${latest_version}/linux-x64/claude" --output "/tmp/claude-installer-${latest_version}"; then
        echo "Failed!" >&2
        exit 1
    fi
    echo "Verifying..."
    actual_size=$(stat -c %s "/tmp/claude-installer-${latest_version}")
    if [ "$actual_size" != "$expected_size" ]; then
        echo "Size mismatch, expected ${expected_size} but was ${actual_size}" >&2
        rm --force "/tmp/claude-installer-${latest_version}"
        exit 1
    fi
    actual_checksum=$(sha256sum "/tmp/claude-installer-${latest_version}" | cut -d' ' -f1)
    if [ "$actual_checksum" != "$expected_checksum" ]; then
        echo "Checksum mismatch, expected ${expected_checksum} but was ${actual_checksum}" >&2
        rm --force "/tmp/claude-installer-${latest_version}"
        exit 1
    fi
    echo "Installing..."
    if ! mkdir -p "${bin_dir}"; then
        echo "Failed to create directory '${bin_dir}'" >&2
        rm --force "/tmp/claude-installer-${latest_version}"
        exit 1
    fi
    if ! mv "/tmp/claude-installer-${latest_version}" "${bin_dir}/claude"; then
        echo "Failed to install new executable as '${bin_dir}/claude'" >&2
        rm --force "/tmp/claude-installer-${latest_version}"
        exit 1
    fi
    chmod +x "${bin_dir}/claude"
    new_version=$(claude --version | sed 's/^\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\) (Claude Code)$/\1/')
    if [ -z "$new_version" ]; then
        echo "Failed to find new version from output of command 'claude'" >&2
        exit 1
    fi
    if [ "$new_version" != "$latest_version" ]; then
        echo "WARNING: The output of command 'claude' indicates this is version ${new_version} and not ${latest_version}"
    else
        echo "Version successfully updated now ${new_version}"
    fi
else
    echo "Existing version ${existing_version} is up to date"
fi

# Extra cleanup of stale PID files from crashed sessions.
# These files are used to keep track of live concurrent REPL sessions (for
# telemetry, not sure if anything else) and when a session ends that deletes
# its own PID file. Crashed session will leave stale files, but normally these
# are cleaned up on next session start. However, this is skipped in WSL, in
# case the directory has been shared with a Claude installation on the Windows
# host, because then it cannot be known from the WSL distro if there is a host
# process with the given PID. Here we assume no such obscure setups are used,
# and therefore performs our own cleaning based on running processes in WSL!
#echo "Cleaning up stale session PID files..."
for pid_file in "${config_dir}/sessions/"*.json; do
    if [ -e "$pid_file" ]; then
        pid=$(basename "$pid_file" .json)
        if echo "$pid" | grep --quiet '^[0-9][0-9]*$'; then
            if ! kill -0 "$pid" 2>/dev/null; then
                echo "Removing stale $pid_file (pid $pid not running)"
                rm "$pid_file"
            fi
        fi
    fi
done

unset bin_dir config_dir
