#!/bin/sh
#
# Installs complete development environment for Go (golang).
#
# Includes supporting tools such as diff, ssh and git.
#
# If the system has not been recently upgraded, which is done automatically
# during setup by the arch-setup (arch-setup-packages) script, to ensure you
# install the latest versions of the packages you should run the arch-upgrade
# script first.
#
# This script does not refresh package database and upgrade existing packages.
# If we were to do it, we would have to be careful not end up in a state of
# partial upgrades (remember to either do both --refresh (-y) and
# --sysupgrade (-u), or none of them, at least never just --refresh (-y)), and
# then there is also the potential issue with signing keys. These are exactly
# things that the arch-upgrade script is handling.
#
# Passes any script arguments to the pacman commands, so can execute script with
# --noconfirm for instance to run non-interactively proceeding without prompting
# user.
#
# NOTE: Assumes basic tools are already installed, including sudo.
# Run script ./arch-setup first to ensure this!
#

# Install packages using utility script arch-dev-base-install.
# It installs base packages by default:
# - Diff command: diffutils
# - SSL toolkit (is also dependency of openssh, git and others): openssl
# - SSH client/server (used with git): openssh
# - Git client: git
# Here we supply additional packages to install as arguments.
"$(dirname "$0")/arch-dev-base-install" "$@" \
    `# Go compiler` \
    go

# GCC compiler (for cgo support)
#    gcc \

# Go dev support tools (but can be installed from VSCode or with "go get" command instead)
#    `# Go basic support tools (goimports, guru, etc)` \
#    go-tools
#    `# Go additional support tools (delve, gopls, staticcheck)` \
#    delve
#    gopls
#    staticcheck

#    `# Fuse library to be able to use cgofuse` \
#    fuse2

#    `# Python 3 (for utility scripts)` \
#    python \
#    python-pylint \
#    python-pytest \
#    ipython \

#    `# Full CMake/Ninja build system for C++` \
#    `# Ninja build-system` \
#    ninja \
#    `# CMake build-system generator` \
#    cmake \

#    `# Alternative Go compiler, based on GCC` \
#    gcc-go
