#!/bin/sh
#
# Installs complete development environment for C++.
#
# Includes GCC, GDB, CMake, Ninja and Boost, as well as supporting tools like
# diff, ssh and git.
#
# If the system has not been recently upgraded, which is done automatically
# during setup by the arch-setup (arch-setup-packages) script, to ensure you
# install the latest versions of the packages you should run the arch-upgrade
# script first.
#
# This script does not refresh package database and upgrade existing packages.
# If we were to do it, we would have to be careful not end up in a state of
# partial upgrades (remember to either do both --refresh (-y) and
# --sysupgrade (-u), or none of them, at least never just --refresh (-y)), and
# then there is also the potential issue with signing keys. These are exactly
# things that the arch-upgrade script is handling.
#
# Passes any script arguments to the pacman commands, so can execute script
# with --noconfirm for instance to run non-interactively proceeding without
# prompting user.
#
# NOTE: Assumes basic tools are already installed, including sudo.
# Run script ./arch-setup first to ensure this!
#
# NOTE: Does not install package group "base-devel", which contains a lot of
# the relevant packages (gcc, binutils, make, grep, sed, sudo etc), instead
# just installs any wanted packages individually, and e.g. binutils will be
# included as dependency of gcc.
#

# Install packages using utility script arch-dev-base-install.
# It installs base packages by default:
# - Diff command: diffutils
# - SSL toolkit (is also dependency of openssh, git and others): openssl
# - SSH client/server (used with git): openssh
# - Git client: git
# Here we supply additional packages to install as arguments.
"$(dirname "$0")/arch-dev-base-install" "$@" \
    `# Boost headers and libraries (includes dependency boost-libs which is also dependency of gdb via source-highlight)` \
    boost \
    `# Ninja build-system` \
    ninja \
    `# CMake build-system generator` \
    cmake \
    `# GCC compiler` \
    gcc \
    `# GDB debugger` \
    gdb

# Possible additions
#    `# Git client LFS extension (not used for now)` \
#    git-lfs \
#    `# CCache (to trade disk space for recompilation speed, not installed for now to avoid it being detected and used before configured properly)` \
#    ccache \
#    `# Valgrind (not used for now, and this is quite large - 320MiB installed)` \
#    valgrind \
#
# # If installing ccache, could then also limit the size from default 5GB to 500MB.
# # Note: This will only have effect for the current user, and will be stored as
# # configuration file ~/.config/ccache/ccache.conf, so must run the script as the
# # intended dev user and not root!
# ccache --set-config max_size=500M
