#!/bin/sh
#
# Cleans the development environment for Claude Code for current user.
#
# This removes global/user data files related to projects, sessions, prompt
# history, file history, various state, plans, cache etc, but keeps the
# important configuration and authentication credentials.
#
# Claude Code persists a lot of session and history data, but cleans up most
# of it automatically, by default after 30 days (e.g. sessions that have been
# inactive this long). The time is configurable with settings.json parameter
# cleanupPeriodDays, and it is considered by session persistence and file
# history. Despite what the documentation says, it seems one can set value 0 to
# turn off the persistence. There is also an undocumented environment variable
# CLAUDE_CODE_SKIP_PROMPT_HISTORY that can be set to turn off the prompt
# history persistence, but also session persistence. Officially there is
# command-line argument --no-session-persistence that claude can be started
# with to disable session persistence for that instance. As of Claude Code
# version 2.1.92, there is no built-in method to get rid of these things on
# demand, and it is not that clear what data is persisted when and for how
# long. This script can be used for a thorough clean to be sure. For an even
# more thorough clean, use the uninstall script and then the install script to
# start completely from scratch.
#
# This also removes any old versions of the application executables from a
# regular setup. At the end, any remaining empty directories from the user home
# will also be removed, assuming if they end up empty after the clean, it was
# Claude Code that created them. The directories considered are commonly used
# Linux directories but do not exist by default in plain Arch Linux filesystem,
# and Claude Code creates them during the regular install procedure, or on
# first start, so should be safe and get us most cleanly back to original state
# if we delete them.
#
# This script considers default locations known to be used by Claude, and also
# environment variables that Claude is known to check for custom locations.
# The defaults are all within the current user's home directory. Claude
# considers environment variable CLAUDE_CONFIG_DIR, falling back to ~/.claude
# for main configuration. It does not consider XDG_CONFIG_HOME. For other
# files, Claude adheres to the XDG standard, considering base directories from
# environment variables XDG_DATA_HOME, XDG_STATE_HOME and XDG_CACHE_HOME,
# falling back to ~/.local/share, ~/.local/state and ~/.cache respectively.
#

# If we could always assume that the distro is always set up with a non-root
# default user, then we could verify we are not running as root, since this
# cleans Claude Code for the current user only.
#if [ ${EUID:-$(id -u)} -eq 0 ]; then
#    echo 'Please do not run this script as root' >&2
#    exit 1
#fi

# Resolve XDG conventional user binary directory.
# This is where the Claude executable is installed by default, and here we
# assume it was not manually installed elsewhere.
bin_dir="${HOME}/.local/bin"

# Resolve Claude-specific configuration directory.
# It is ~/.claude by default, and can be overridden by variable
# CLAUDE_CONFIG_DIR, Claude does not consider XDG_CONFIG_HOME.
config_dir="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"

# Resolve XDG standard base directories, falling back to XDG defaults.
# Ignoring XDG_CONFIG_HOME as per comment above.
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
state_home="${XDG_STATE_HOME:-$HOME/.local/state}"
cache_home="${XDG_CACHE_HOME:-$HOME/.cache}"

# Delete old versions of the application executables from regular setup.
# If not currently regular setup, then all executables in the version store
# will be removed.
echo "Cleaning up application files..."
echo "Considering binary directory '${bin_dir}'"
echo "Considering data directory '${data_home}'"
find "${data_home}/claude/versions" -maxdepth 1 -type f -not -path "$(readlink -e "${bin_dir}/claude")" -delete 2> /dev/null

# Remove data files.
# Currently deleting using include strategy, but could consider changing to
# exclude strategy, e.g. from $config_dir probably everything except files
# CLAUDE.md, settings.json, .credentials.json, policy-limits.json,
# keybindings.json should be deleted?
echo "Cleaning up data files..."
echo "Considering configuration directory '${config_dir}'"
echo "Considering cache directory '${cache_home}'"
echo "Considering state directory '${state_home}'"
rm --recursive --force "${config_dir}/backups"
rm --recursive --force "${config_dir}/cache"
rm --recursive --force "${config_dir}/debug"
rm --recursive --force "${config_dir}/downloads"
rm --recursive --force "${config_dir}/file-history"
rm --recursive --force "${config_dir}/image-cache"
rm --recursive --force "${config_dir}/paste-cache"
rm --recursive --force "${config_dir}/plans"
rm --recursive --force "${config_dir}/projects"
rm --recursive --force "${config_dir}/session-env"
rm --recursive --force "${config_dir}/sessions"
rm --recursive --force "${config_dir}/shell-snapshots"
rm --recursive --force "${cache_home}/claude"
rm --recursive --force "${cache_home}/claude-cli-nodejs"
rm --recursive --force "${state_home}/claude"
rm --force "${config_dir}/history.jsonl"

# Cleanup remaining empty directories.
# Note that the base directories themselves will also be deleted if left empty.
# In a clean distro install these typically do not exist, so if left empty we
# are just assuming the Claude install created them.
echo "Cleaning up remaining empty directories..."
find "${config_dir}" -type d -empty -delete 2> /dev/null
find "${data_home}" -type d -empty -delete 2> /dev/null
find "${state_home}" -type d -empty -delete 2> /dev/null
find "${cache_home}" -type d -empty -delete 2> /dev/null

unset bin_dir config_dir data_home state_home cache_home
