#!/bin/sh
#
# Minimize filesystem.
#
# This variant keeps locale-specific content only for built-in locales and
# the UTF-8 character set.
#
# Deleting unnecessary files, and configuring pacman to not reinstall them.
# Creates file /etc/pacman.d/noextract, and includes it from /etc/pacman.conf.
#
# As an example, this reduced initial filesystem size from 535M to 429M.
#
# Note: Doing this early, to avoid installing unnecessary files, but then
# when updating /etc/pacman.conf we may not have grep available to check
# if already exists, so will then fallback to simple line search - which
# may fail and lead to duplicate import, but this should not corrupt the
# pacman config.
#

# Verify running as root (not relying on sudo which may not be installed yet).
if [ ${EUID:-$(id -u)} -ne 0 ]; then
    echo 'Please run this script as root'
    exit 1
fi

# Localizations
rm -r /usr/share/locale/* > /dev/null 2>&1
# Internationalizations
find /usr/share/i18n/locales -mindepth 1 -maxdepth 1 -type f -not -name 'C' -not -name 'POSIX' -not -name 'i18n' -not -name 'i18n_ctype' -not -name 'iso14651_t1' -not -name 'iso14651_t1_common' -not -name 'translit_*' -delete
# Character sets
find /usr/share/i18n/charmaps -mindepth 1 -maxdepth 1 -type f -not -name UTF-8.gz -delete
# Documentation
rm -r /usr/share/doc/* /usr/share/info/* /usr/share/gtk-doc/html/* /usr/share/man/* > /dev/null 2>&1
# Licenses
rm -r /usr/share/licenses/* > /dev/null 2>&1
# Supplementary files included in the file system root directory of some of the bootstrap distributions:
# - 2021.01.01 included a README file
# - 2022.01.01 included files version and pkglist.x86_64.txt, but no README file
# - 2025.01.01 included version file only (pkglist.x86_64.txt was moved outside of the file system root)
# - 2026.01.01 included none (version was moved moved outside of the file system root together with pkglist.x86_64.txt)
rm /README /version /pkglist.x86_64.txt > /dev/null 2>&1

# Make sure file /etc/pacman.d/noextract is generated with NoExtract options preventing reinstall removed files
if [ -f "/etc/pacman.d/noextract" ]; then
    echo "Skipping generation of pacman NoExtract options: File /etc/pacman.d/noextract already exists"
    cat /etc/pacman.d/noextract
    echo ""
else
    echo "Generating pacman NoExtract options in separate file /etc/pacman.d/noextract"
    cat <<EOF > /etc/pacman.d/noextract
[options]
NoExtract = usr/share/locale/*
NoExtract = usr/share/i18n/locales/* !usr/share/i18n/locales/C !usr/share/i18n/locales/POSIX !usr/share/i18n/locales/i18n !usr/share/i18n/locales/i18n_ctype !usr/share/i18n/locales/iso14651_t1 !usr/share/i18n/locales/iso14651_t1_common !usr/share/i18n/locales/translit_*
NoExtract = usr/share/i18n/charmaps/* !usr/share/i18n/charmaps/UTF-8.gz
NoExtract = usr/share/doc/* usr/share/info/* usr/share/gtk-doc/html/* usr/share/man/*
NoExtract = usr/share/licenses/*
EOF
fi

# Make sure file /etc/pacman.d/noextract is included in /etc/pacman.conf
noextract_import_missing=1
if command -v grep > /dev/null; then
    # Grep is available, we can use it with a regular expression to be leanient on space characters etc
    grep --quiet '^\s*Include\s*=\s*/etc/pacman.d/noextract\s*$' /etc/pacman.conf
    noextract_import_missing=$?
else
    # Grep is not available, we search file for exact match of line
    while read -r line; do
        if [ "$line" = "Include = /etc/pacman.d/noextract" ]; then
            noextract_import_missing=0
            break
        fi
    done < /etc/pacman.conf
fi
if [ "$noextract_import_missing" -eq 0 ]; then
    echo "Skipping pacman.conf noextract configuration: Include of /etc/pacman.d/noextract is already present in /etc/pacman.conf"
else
    echo "Adding include of /etc/pacman.d/noextract to pacman.conf"
    echo 'Include = /etc/pacman.d/noextract' >> /etc/pacman.conf
fi
unset noextract_import_missing
