#!/bin/sh
#
# Configure pacman.
#
# Assuming this script is run immediately after a clean install, we must ensure
# that pacman is configured to be able to install the packages we want.
# Therefore we start by configuring a package repository mirror, and then
# initialize the pacman keyring.
#
# When setting mirror, this moves away any existing mirrorlist file by adding
# suffix .old.<random>, and then creates a new file with a single specific
# mirror. Will try to check if the mirror is already enabled in the file, but
# does not assume tools grep, sed or awk are available to perform this check
# properly, because in old versions of the bootstrap archive they were not
# included, and of course we need to setup pacman before we can install them
# (see arch-setup-packages). If none of the tools are available, then using a
# fallback method which is very simplistic and may end up recreating the file
# unnecessary.
#
# On a clean bootstrap archive there is a default mirrorlist file that contains
# all mirrors commented out. The official Arch WSL distro bundles a custom
# mirrorlist file with two mirrors configured. It currently prefers the
# worldwide CDN mirror from Fastly, a sponsor of the Arch project providing
# Hosting/CDN services. This mirror is not a traditional mirror, but a Content
# Delivery Network service, caching content directly from the authorative
# source mirror.pkgbuild.com that is running on the Arch Linux Team's own
# infrastructure. Previously the default mirrorlist was configured with the
# Arch Linux Team's own worldwide GeoDNS mirror service, distributing requests
# directly to a specific regional subdomain of mirror.pkgbuild.com based on
# location, and this is still kept as a fall-back, but Fastly is now considered
# a better and faster alternative. The bundled mirrorlist file looks like this:
#   Server = https://fastly.mirror.pkgbuild.com/$repo/os/$arch
#   Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
# Rackspace is another worldwide mirror with strong reputation, historically
# used a lot as a default or fall-back:
#   Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
# Here we use the Fastly CDN as default, but variable ARCH_SETUP_MIRROR can be
# set to use something else. Note that this must be the address only to the
# root of the mirror server and without trailing slash, e.g.
# "https://fastly.mirror.pkgbuild.com", as "/$repo/os/$arch" will be appended
# when written to the mirrorlist file.
#
# On a clean system installed from bootstrap archive there should be no keys,
# i.e. no folder /etc/pacman.d/gnupg, but in case we have tried before without
# luck we delete it which forces resetting of all keys as described here:
# https://wiki.archlinux.org/index.php/Pacman/Package_signing#Resetting_all_the_keys
#
# When using the official WSL distro a similar task may have already been done:
# It has preconfigured a couple of default urls in the bundled mirrorlist file,
# and on first startup it initializes the pacman keyring. In this case we will
# still just reset all keys (although unnecessary at this point) and create a
# new mirrorlist file (with our own preferred urls), as described above.
#
# The "pacman-key --init" command executed below will on a clean install of
# bootstrap archive as of 2021.02.01 report an error due to missing awk
# command. It does enough that "pacman-key --populate archlinux" can be run
# next (and that fails without the initial "pacman-key --init"), after which
# we are able to install packages (which we can not without these two
# commands). Don't know the state of the generated keys in this situation, so
# would probably want to install gawk and reset the keys as described here:
# https://wiki.archlinux.org/index.php/Pacman/Package_signing#Resetting_all_the_keys
# But gawk is actually installed by default, it is just not not available as
# "awk"! There is a symlink /usr/bin/awk pointing to /usr/bin/gawk, but
# /usr/bin/gawk does not exist, while there is an executable
# /usr/bin/gawk-5.1.0 which does! So we find it and copy it into /usr/bin/awk
# (or rather /usr/bin/gawk which /usr/bin/awk is an symlink to). Reinstalling
# the gawk package would have done the same.
#

# Verify running as root (not relying on sudo which may not be installed yet).
if [ ${EUID:-$(id -u)} -ne 0 ]; then
    echo 'Please run this script as root' >&2
    exit 1
fi

# Make sure awk is linked.
# It is required by pacman-key --init as described above.
# We can therefore also rely on it when checking mirror configuration before
# running the pacman-key --init command!
awk=/usr/bin/awk
if [ -e "$awk" ]; then
    if [ -x "$awk" ]; then
        echo "Required awk command found at $awk";
    else
        # Strange - it exists but is not an executable file!?
        echo "WARNING: Required awk command not found, 'pacman-key --init' will probably report an error. When this script is completed, you should consider resetting all the pacman keys as described here: https://wiki.archlinux.org/index.php/Pacman/Package_signing#Resetting_all_the_keys"
    fi
else
    # Find any *awk* executable in /usr/bin.
    realawk=$(find /usr/bin -type f -executable -name "*awk*" -print -quit)
    if [ -z "$realawk" ]; then
        echo "WARNING: Required awk command not found, 'pacman-key --init' will probably report an error. When this script is completed, you should consider resetting all the pacman keys as described here: https://wiki.archlinux.org/index.php/Pacman/Package_signing#Resetting_all_the_keys"
    else
        # Found an alternative awk command, e.g. /usr/bin/gawk-5.1.0, make a copy of that as /usr/bin/awk.
        if [ -h "$awk" ]; then
            # Primary awk command path exists but is a symlink to non-existing file.
            # Locate the target of the symlink, so we can copy into that instead
            # of replacing the symlink!
            awk=$(readlink --canonicalize --no-newline /usr/bin/awk)
        fi
        echo "NOTICE: Required awk command missing but found $realawk, so will copy it to $awk"
        cp "$realawk" "$awk"
    fi
    unset realawk
fi
unset awk

# Configure package repository mirror.
# If there is an existing mirrorlist file, we check if the requested package
# repository mirror is the first, or primary, of all active/uncommented
# mirror configuration lines (pacman tries mirrors in the order they appear in
# the mirrorlist file). If not, then we rename this mirrorlist file to .old
# followed by some random numbers, and create a new. Pacman will typically also
# create file mirrorlist.pacnew on update, so this strategy is sort of in line
# with that.
# Note: Doing this first, before the "pacman-key --init" command, because it
# uses this, and if the file does not exist it will report an error (but continue):
#   error: config file /etc/pacman.d/mirrorlist could not be read: No such file or directory
mirrorhost=${ARCH_SETUP_MIRROR:-https://fastly.mirror.pkgbuild.com}
mirrorconfig="Server = ${mirrorhost}/\$repo/os/\$arch"
echo "Configuring package repository mirror ${mirrorhost}"
if [ -f "/etc/pacman.d/mirrorlist" ]; then
    # Making no assumptions, grep was not always included in the bootstrap
    # archive, and we need to setup pacman before we can install any additional
    # tools (see arch-setup-packages).
    if command -v grep > /dev/null 2>&1; then
        mirrorlist=$(grep '^Server = ' /etc/pacman.d/mirrorlist)
    elif command -v sed > /dev/null 2>&1; then
        mirrorlist=$(sed -n '/^Server = /p' /etc/pacman.d/mirrorlist)
    elif command -v awk > /dev/null 2>&1; then
        mirrorlist=$(awk '/^Server = /' /etc/pacman.d/mirrorlist)
    else
        echo "WARNING: Doing a simplistic check for existing configuration because grep/sed/awk is missing"
        mirrorlist="$(tail --lines=1 /etc/pacman.d/mirrorlist 2> /dev/null)"
    fi
    if [ -z "$mirrorlist" ]; then
        mirrorcount=0
    else
        mirrorcount=$(echo "$mirrorlist" | wc -l)
    fi
    echo "Mirrorlist file exists with ${mirrorcount} active mirror(s) configured"
    if [ -n "$mirrorlist" ]; then
        echo "$mirrorlist"
    fi
    if [ "$(echo "$mirrorlist" | head -1)" = "$mirrorconfig" ]; then
        echo "The requested mirror is already configured as primary"
        echo "Keeping existing mirrorlist file unchanged"
        if [ "$mirrorcount" -gt 1 ]; then
            echo "WARNING: There are additional lower priority mirrors configured (${mirrorcount} in total)"
        fi
    else
        echo "The requested mirror is not already configured as primary"
        mirrorlist_backup=$(mktemp --tmpdir=/etc/pacman.d mirrorlist.old.XXXXX)
        echo "Moving existing mirrorlist file out of the way as '$mirrorlist_backup'"
        if ! mv /etc/pacman.d/mirrorlist "$mirrorlist_backup"; then
            echo "Failed!" >&2
            exit 1
        fi
        echo "Writing new mirrorlist file with only the requested mirror"
        if ! echo "$mirrorconfig" > /etc/pacman.d/mirrorlist; then
            echo "Failed!" >&2
            echo "Trying to restore backup" >&2
            if ! mv "$mirrorlist_backup" /etc/pacman.d/mirrorlist; then
                echo "Failed!" >&2
                echo "Please check '/etc/pacman.d/mirrorlist' and compare with original backup '${mirrorlist_backup}'" >&2
            fi
            exit 1
        fi
        unset mirrorlist_backup
    fi
    unset mirrorcount mirrorlist
else
    echo "Writing new mirrorlist file"
    if ! echo "$mirrorconfig" > /etc/pacman.d/mirrorlist; then
        echo "Failed!" >&2
        exit 1
    fi
fi
unset mirrorconfig mirrorhost

# Initialize pacman.
if [ -e /etc/pacman.d/gnupg ]; then
    echo "NOTICE: Existing pacman keys will be reset" # In case we have tried before without luck!?
    rm -rf /etc/pacman.d/gnupg
fi
pacman-key --init
pacman-key --populate > /dev/null
