#!/bin/sh
#
# Configure pacman.
#
# Assuming this script is run immediately after a clean install, we must ensure
# that pacman is configured to be able to install the packages we want.
# Therefore we start by intializing the pacman keyring, and then configures url
# to a repository server (mirror).
#
# On a clean system installed from bootstrap archive there should be no keys, i.e. no
# folder /etc/pacman.d/gnupg, but in case we have tried before without luck we delete
# it which forces resetting of all keys as described here:
# https://wiki.archlinux.org/index.php/Pacman/Package_signing#Resetting_all_the_keys
#
# When setting mirror, this just moves away the existing mirrorlist file to .old.<random>,
# and then creates a new file with a hard coded url. Does not have tools such as grep
# or sed to check if there are already mirrors enabled in the file (the default
# mirrorlist contains all mirrors commented out).
# TODO: We could have used gawk, see below (but we may or may not find it..?)
#
# When using the official WSL distro a similar task have already been done: It has
# preconfigured a couple of default urls in the bundled mirrorlist file, and on first
# startup it initializes the pacman keyring. In this case we will still just reset
# all keys (although unnecessary at this point) and create a new mirrorlist file (with
# our own preferred urls), as described above.
#
# The "pacman-key --init" command executed below will on a clean install of bootstrap
# archive as of 2021.02.01 report an error due to missing awk command. It does enough
# that "pacman-key --populate archlinux" can be run next (and that fails without the
# initial "pacman-key --init"), after which we are able to install packages (which we
# can not without these two commands). Don't know the state of the generated keys in
# this sitation, so would probably want to install gawk and reset the keys as
# described here: https://wiki.archlinux.org/index.php/Pacman/Package_signing#Resetting_all_the_keys
# But gawk is actually installed by default, it is just not not available as "awk"!
# There is a symlink /usr/bin/awk pointing to /usr/bin/gawk, but /usr/bin/gawk does
# not exist, while there is an executable /usr/bin/gawk-5.1.0 which does! So we find
# it and copy it into /usr/bin/awk (or rather /usr/bin/gawk which /usr/bin/awk is an
# symlink to). Reinstalling the gawk package would have done the same.
#

# Verify running as root (not relying on sudo which may not be installed yet).
if [ ${EUID:-$(id -u)} -ne 0 ]; then
    echo 'Please run this script as root'
    exit 1
fi

# Make sure awk is linked
awk=/usr/bin/awk
if [ -e "$awk" ]; then
    if [ -x "$awk" ]; then
        echo "Required awk command found at $awk";
    else
        # Strange - it exists but is not an executable file!?
        echo
        echo "WARNING: Required awk command not found, 'pacman-key --init' will probably report an error. When this script is completed, you should consider resetting all the pacman keys as described here: https://wiki.archlinux.org/index.php/Pacman/Package_signing#Resetting_all_the_keys"
        echo
    fi
else
    # Find any *awk* executable in /usr/bin
    realawk=$(find /usr/bin -type f -executable -name "*awk*" -print -quit)
    if [ -z "$realawk" ]; then
        echo
        echo "WARNING: Required awk command not found, 'pacman-key --init' will probably report an error. When this script is completed, you should consider resetting all the pacman keys as described here: https://wiki.archlinux.org/index.php/Pacman/Package_signing#Resetting_all_the_keys"
        echo
    else
        # Found an alternative awk command, e.g. /usr/bin/gawk-5.1.0, make a copy of that as /usr/bin/awk.
        if [ -h "$awk" ]; then
            # Primary awk command path exists but is a symlink to non-existing file.
            # Locate the target of the symlink, so we can copy into that instead
            # of replacing the symlink!
            awk=$(readlink --canonicalize --no-newline /usr/bin/awk)
        fi
        echo "NOTICE: Required awk command missing but found $realawk, so will copy it to $awk"
        cp $realawk $awk
    fi
fi

# Initialize pacman
if [ -e /etc/pacman.d/gnupg ]; then
    echo "NOTICE: Existing pacman keys will be reset" # In case we have tried before without luck!?
    rm -rf /etc/pacman.d/gnupg
fi
pacman-key --init
pacman-key --populate > /dev/null

# Configure package repository mirror
# Currently using a Norwegian mirror, provided by the Norwegian Student's Society, based in Oslo. It is a
# Tier 1 mirror of high quality and performance (at least from northern Europe), and it is not controlled
# by a commercial company. The mirorlist file looks like this:
#   Server = https://mirror.neuf.no/archlinux/$repo/os/$arch
# The official Arch WSL distro currently prefers the worldwide CDN mirror from Fastly, a sponsor of the Arch
# project providing Hosting/CDN services. Previously it used their own worldwide GeoDNS mirror service, which
# resolves to an actual mirror based on location. This is now used as fall-back. The bundled mirrorlist file
# looks like this:
#   Server = https://fastly.mirror.pkgbuild.com/$repo/os/$arch
#   Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
# Rackspace is another worldwide mirror, historically used a lot as a default:
#   Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
if [ "$(tail --lines=1 /etc/pacman.d/mirrorlist 2> /dev/null)" == "Server = https://mirror.neuf.no/archlinux/\$repo/os/\$arch" ]; then
    echo "Package repository mirror already in mirrorlist";
else
    if [ -e "/etc/pacman.d/mirrorlist" ]; then
        mirrorlist_backup=$(mktemp --tmpdir=/etc/pacman.d mirrorlist.old.XXXXX)
        echo "Moving existing mirrorlist file out of the way: $mirrorlist_backup"
        mv /etc/pacman.d/mirrorlist $mirrorlist_backup
    fi
    echo "Writing package repository mirror to new mirrorlist file"
    echo "Server = https://mirror.neuf.no/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
fi
