#!/bin/sh
#
# Installs development environment for Go (golang), including gcc (for cgo),
# and supporting tools such as git.
#
# Also performs refresh of package database and upgrade of existing packages to ensure
# we get latest versions. Runs with the -Syu option, which seems to be the recommended
# approach for normal upgrades on arch, not -Syuu which may also downgrade packages. In
# any case, remember to either do both --refresh (-y) and --sysupgrade (-u), or none of
# them, at least never --refresh (-y) which will easily lead to the partial upgrades syndrome!
#
# Passes any script arguments to the pacman commands, so can execute script with
# --noconfirm for instance to run non-interactively proceeding without prompting
# user.
#
# NOTE: Assumes basic tools are already installed, including sudo.
# Run script ./arch-init first to ensure this!
#

echo "Updating package database, upgrading existing packages, and installing new packages..."
sudo pacman --sync --refresh --sysupgrade --needed "$@" \
    `# Diff command` \
    diffutils \
    `# SSL toolkit (is also dependency of openssh, git and others)` \
    openssl \
    `# SSH client/server (used with git)` \
    openssh \
    `# Git client` \
    git \
    `# GCC compiler` \
    gcc \
    `# Go compiler` \
    go
    

# Go dev support tools (but can be installed from VSCode or with "go get" command instead)
#    `# Go basic support tools (goimports, guru, etc)` \
#    go-tools
#    `# Go additional support tools (delve, gopls, staticcheck)` \
#    delve
#    gopls
#    staticcheck


#    `# Fuse library to be able to use cgofuse` \
#    fuse2

#    `# Full CMake/Ninja build system for C++` \
#    `# Ninja build-system` \
#    ninja \
#    `# CMake build-system generator` \
#    cmake \

#    `# Alternative Go compiler, based on GCC` \
#    gcc-go

echo
echo "Cleaning package cache..."
if ! pacman --sync --clean "$@"; then
    echo "Failed!"
    exit 1
fi
