#!/bin/sh
#
# Force package database update, perform full package upgrade/downgrade, and install basic utilities.
#
# This is intended for initial setup. For later upgrades, use arch-upgrade or
# arch-upgrade-full instead. This script does everything that arch-upgrade-full
# does, except this does not rely on sudo (which may not be installed yet) and
# must therefore be run as root, and it does the additional task of checking the
# timezone database and installing basic utilities if missing.
#
# This takes a thorough, robust and clean approach. It accounts for changes to
# the signing keys, which may otherwise lead to errors such as "unknown trust"
# or "marginal trust" during package upgrades, especially if the system is not
# upgraded regularly. The solution is to manually sync the package database and
# upgrade the archlinux-keyring package before upgrading other packages. Then it
# upgrades all other packages, without performing an unnecessary extra sync of
# the package database. After that, it performs cleanup by removing (uninstalling)
# any packages that are no longer required, considering packages that were not
# explicitly installed, but originally installed as a dependency of other packages,
# even as an optional dependency. When dependency relations are removed as part of a
# packages upgrade, the dependent packages are normally left behind. These are also
# known as orphans. Finally, it cleans up the package database (cache), removing
# packages that are no longer installed to free up disk space.
#
# Passes any script arguments to the pacman commands, so can execute script with
# --noconfirm for instance to run non-interactively proceeding without prompting
# user.
#
# Remember to either do both --refresh (-y) and --sysupgrade (-u), or none of them,
# at least never just --refresh (-y) which will easily lead to the partial upgrades syndrome!
#

# Verify running as root (not relying on sudo which may not be installed yet).
if [ ${EUID:-$(id -u)} -ne 0 ]; then
    echo 'Please run this script as root'
    exit 1
fi

#
# Force update the package database.
# Will refresh even if it appear to be up-to-date, due to double --refresh.
#
# Note that this is a bit bit dangerous to do without upgrading packages as
# well, since it may lead to a bad state of partial upgrades, but it is
# intentional because we want to install/upgrade the keyring package first,
# before we upgrade all packages.
#
echo
echo "Forcing update of package database..."
if ! pacman --sync --refresh --refresh "$@"; then
    echo "Failed!"
    exit 1
fi

#
# Ensure keyring contains the latest official set of packager keys.
#
# The package archlinux-keyring contains the official set of keys. Assuming
# it is preinstalled: Newer versions of Arch comes with the "base" meta package
# preinstalled, and newer versions of that includes the archlinux-keyring package.
# Previously the archlinux-keyring package would be implicitely included as pacman
# version 6.0.1-5 and older had a dependency to it, but pacman version 6.0.1-6
# removed the dependency to archlinux-keyring, and archlinux-keyring version
# 20220713-2 added dependency to pacman instead, and then base version 3-1 was
# extended to include archlinux-keyring in addition to pacman.
#
echo
echo "Ensuring latest keyring package is installed..."
if ! pacman --sync --needed "$@" archlinux-keyring; then
    echo "Failed!"
    echo "NOTE: The package database was previously successfully updated, but due to this"
    echo "error when attempting to install/upgrade the keyring package, existing packages"
    echo "have not been upgraded! Make sure to repeat this script until it succeeds, at"
    echo "least do not install any new packages before existing packages has been"
    echo "successfully upgraded, or else you may get into a bad state of partial upgrades!"
    exit 1
fi

#
# Force upgrade/downgrade any modified packages.
#
# Not performing another database refresh at this point, could add --refresh to do that,
# and even twice if we wanted to force the refresh.
#
# Allowing downgrading packages to match the version currently in cache with
# double --sysupgrade options, which are usually only relevant when switching package
# repositories and performing a full upgrade. It will interactively prompt for confirmation
# before proceeding should any be found, which could be avoided by adding --noconfirm.
#
echo
echo "Performing full upgrade/downgrade of packages..."
if ! pacman --sync --sysupgrade --sysupgrade "$@"; then
    echo "Failed!"
    echo "NOTE: The package database was previously successfully updated, but since the"
    echo "upgrading of existing packages failed, make sure to repeat this script until it"
    echo "succeeds, at least do not install any new packages before existing packages has"
    echo "been successfully upgraded, or else you may get into a bad state of partial"
    echo "upgrades!"
    exit 1
fi

#
# Ensure complete timezone database.
#
# In the bootstrap archive as of version 2021.02.01, the tzdata package was
# already installed, as dependency to glibc, but incomplete, missing about 800
# of 2500 files, as revealed by command "pacman --query --check tzdata".
# This includes timezone definitions for Europe/Rome, Europe/Moscow, Europe/London,
# Europe/Dublin and Europe/Oslo.
# WSL automatically sets the timezone of the distro, it creates the /etc/localtime
# symlink to the proper file under /usr/share/zoneinfo matching the configured
# timezone in Windows. But if the timezone to be configured does not exist then
# the distro will be left with UTC. To ensure timezone are set up, we reinstall
# the tzdata package (no --needed argument) to ensure we have the complete set!
# This may have changed in newer versions, and the situation may also be different
# in other distributions, e.g. in the official WSL distro version 2026.03.01 the
# tzdata package is complete, however then our check first will detect this and
# just skip with the message that the timezone database is complete, so it should
# be safe.
#
echo
echo "Checking timezone database..."
if ! pacman --query --check --quiet tzdata > /dev/null; then
    echo "Reinstalling timezone database to get missing zoneinfo files"
    echo "NOTICE: Ignore warning \"is up to date -- reinstalling\""
    if ! pacman --sync "$@" tzdata; then
        echo "Failed!"
        exit 1
    fi
    echo "Success (ignore all warnings \"could not get file information\")"
    restart_required=1 # Flag to "caller", i.e. arch-setup when sourcing this script
    echo "NOTICE: Restarting is required for the changes to be applied!"
else
    echo "Timezone database is complete"
fi

#
# Install some basic utilities.
#
# Arch linux contains basically only the most necessary system tools required for
# system startup, but the newer versions of the bootstrap archive (tested
# 2022.07.01) comes with the meta package "base" preinstalled. It includes some
# additional system tools that are highly relevant base utilities in any
# installation, and typically assumed to be part of any Arch installation.
# Therefore we can assume packages such as the following are already installed:
# shadow, systemd, pacman, pacman-mirrorlist, archlinux-keyring, ca-certificates,
# bash, sed, grep, gawk, tar, gzip, bzip2, xz, zlib, openssl, curl, iputils,
# iproute2, procps-ng.
#
# Here we install some additional tools which cannot be assumed to be included
# in a clean minimal installation, such as sudo, unzip, wget, nano.
# Could consider 7zip, which is now the official 7-zip.org version, instead of
# unzip, although it is relatively much bigger (6.25 vs 0.3 MiB).
#
# Previously the bootstrap archive did not include the "base" package, e.g.
# version 2021.02.01 included: pacman, pacman-mirrorlist, ca-certificates, bash,
# openssl, curl, gawk, bzip2, xz and zlib, but it did not include sudo, sed, grep,
# tar, gzip, unzip, wget, nano, iputils, iproute2, procps-ng. Also the "base" was
# previously a package group and not a meta package, and it included more packages.
# The base package group could then be installed to get tar, gzip, sed, shadow,
# systemd, grep, iputils (with ping command), procps-ng (with ps command) etc.
# (some overlap with preinstalled). To leave a slimmer installation this script
# did not install the base package, but only some of the individual packages found
# to be needed.
#
# NOTE: Remember to either do both --refresh (-y) and --sysupgrade (-u), or none of them,
# at least never --refresh (-y) which will easily lead to the partial upgrades syndrome!
# Here we do none, update and upgrade was performed as a separate step above, so now
# we can just install packages according to the current package database.
#
echo
echo "Installing basic packages..."
if ! pacman --sync --needed "$@" \
    `# Packages included in meta package "base" which is preinstalled on newer bootstrap images (TODO: Remove)` \
    sed \
    grep \
    tar \
    gzip \
    iputils \
    iproute2 \
    procps-ng \
    `# Packages not preinstalled` \
    sudo \
    unzip \
    wget \
    nano
then
    echo "Failed!"
    exit 1
fi

#
# Uninstall any unrequired packages left behind (orphans).
# Considering packages that were not explicitly installed, but originally installed as a
# dependency of other packages, even as an optional dependency due to the double --unrequired.
#
echo
echo "Cleaning up unrequired packages..."
#echo "* Note that when none are found it is expected to see \"error: argument '-' specified with empty stdin\""
#pacman --query --deps --unrequired --unrequired --quiet | sudo pacman --remove --nosave --recursive "$@" -
if orphans=$(pacman --query --deps --unrequired --unrequired --quiet) && [ -n "$orphans" ]; then
    # This works, assuming default IFS lead to correct splitting of argument, and because in Arch:
    # Package names can contain only alphanumeric characters and any of @, ., _, +, -. Names are not
    # allowed to start with hyphens or dots. All letters should be lowercase.
    sudo pacman --remove --nosave --recursive "$@" $orphans
fi
unset orphans

#
# Clean the package database (cache).
# Removing packages that are no longer installed to free up disk space.
# To completely delete the database, also packages that are currently installed, we could
# add another --clean.
# This will interactively prompt for confirmation before proceeding, unless --noconfirm
# is also added.
#
echo
echo "Cleanup package cache..."
if ! pacman --sync --clean "$@"; then
    echo "Failed!"
    exit 1
fi
