#!/bin/sh
#
# Installs complete development environment for Python.
#
# Includes the commonly used Python libraries NumPy, Pylint and pytest, the
# enhanced interactive command shell IPython, and supporting tools such as
# diff, ssh and git.
#
# If the system has not been recently upgraded, which is done automatically
# during setup by the arch-setup (arch-setup-packages) script, to ensure you
# install the latest versions of the packages you should run the arch-upgrade
# script first.
#
# This script does not refresh package database and upgrade existing packages.
# If we were to do it, we would have to be careful not end up in a state of
# partial upgrades (remember to either do both --refresh (-y) and
# --sysupgrade (-u), or none of them, at least never just --refresh (-y)), and
# then there is also the potential issue with signing keys. These are exactly
# things that the arch-upgrade script is handling.
#
# Passes any script arguments to the pacman --sync command, so can execute
# script with name of additional packages as arguments, and with --noconfirm to
# run non-interactively proceeding without prompting user.
#
# NOTE: Assumes basic tools are already installed, including sudo.
# Run script ./arch-setup first to ensure this!
#

# Install packages using utility script arch-dev-base-install.
# It installs base packages by default:
# - Diff command: diffutils
# - SSL toolkit (is also dependency of openssh, git and others): openssl
# - SSH client/server (used with git): openssh
# - Git client: git
# Here we supply additional packages to install as arguments.
"$(dirname "$0")/arch-dev-base-install" "$@" \
    `# Python (with dependencies openssl, mpdecimal and more)` \
    python \
    `# NumPy (with dependencies blas, cblas and lapack)` \
    python-numpy \
    `# Pylint (with dependencies python-astroid, python-colorama, python-dill,` \
    `# python-isort, python-setuptools, python-jaraco.collections, python-jaraco.functools,` \
    `# python-jaraco.text, python-autocommand, python-more-itertools, python-packaging,` \
    `# python-wheel, python-pkg_resources, python-typing_extensions, python-mccabe,` \
    `# python-platformdirs, python-tomlkit)` \
    python-pylint \
    `# pytest (with dependencies python-iniconfig, python-packaging, python-pluggy, python-pygments)` \
    python-pytest \
    `# IPython (with dependencies python-argcomplete, python-asttokens, python-decorator,` \
    `# python-executing, python-ipython-pygments-lexers, python-jedi, python-matplotlib-inline,` \
    `# python-parso, python-pexpect, python-prompt_toolkit, python-ptyprocess, python-pure-eval,` \
    `# python-pygments, python-stack-data, python-traitlets, python-typing_extensions, python-wcwidth)` \
    ipython
