#!/bin/sh
#
# Installs basic development environment.
#
# Includes general supporting tools such as diff, ssh and git.
#
# May be used as a base for setting up more specific development environments,
# and then this script can also be executed with name of the additional
# packages as arguments.
#
# If the system has not been recently upgraded, which is done automatically
# during setup by the arch-setup (arch-setup-packages) script, to ensure you
# install the latest versions of the packages you should run the arch-upgrade
# script first.
#
# This script does not refresh package database and upgrade existing packages.
# If we were to do it, we would have to be careful not end up in a state of
# partial upgrades (remember to either do both --refresh (-y) and
# --sysupgrade (-u), or none of them, at least never just --refresh (-y)), and
# then there is also the potential issue with signing keys. These are exactly
# things that the arch-upgrade script is handling.
#
# This script does not perform cleanup, e.g. by running a 'pacman --sync --clean'
# command. Since it does not upgrade existing packages, there should not be any
# more packages in cache that are no longer installed than it was before. The
# arch-upgrade script does cleanup, where it is more relevant. This also makes
# the argument handling in this script much simpler, as any arguments are passed
# only to a single pacman command.
#
# Passes any script arguments to the pacman --sync command, so can execute
# script with name of additional packages as arguments, and with --noconfirm to
# run non-interactively proceeding without prompting user.
#
# NOTE: Assumes basic tools are already installed, including sudo.
# Run script ./arch-setup first to ensure this!
#

echo "Installing packages..."
if ! sudo pacman --sync --needed "$@" \
    `# Diff command` \
    diffutils \
    `# SSL toolkit (is also dependency of openssh, git and others)` \
    openssl \
    `# SSH client/server (used with git)` \
    openssh \
    `# Git client` \
    git
then
    echo "Failed!" >&2
    exit 1
fi
