#!/bin/sh
#
# Create convenience aliases for Claude Code for current user.
#
# Note: This is not done automatically on install, and therefore uninstall will
# not remove them either.
#

# If we could always assume that the distro is always set up with a non-root
# default user, then we could verify we are not running as root, since this
# considers a local Claude Code installation for the current user only!
#if [ ${EUID:-$(id -u)} -eq 0 ]; then
#    echo 'Please do not run this script as root' >&2
#    exit 1
#fi

"$(dirname "${0}")/arch-dev-claude-aliases" "$@" \
    "ccu=$(realpath "$(dirname "$0")/arch-dev-claude-standalone-upgrade")" \
    "ccun=$(realpath "$(dirname "$0")/arch-dev-claude-standalone-upgrade") --noconfirm"
