#!/bin/sh
#
# Installs complete development environment for C++, Python and Qt.
#
# Includes supporting tools such as diff, ssh and git.
#
# If the system has not been recently upgraded, which is done automatically
# during setup by the arch-setup (arch-setup-packages) script, to ensure you
# install the latest versions of the packages you should run the arch-upgrade
# script first.
#
# This script does not refresh package database and upgrade existing packages.
# If we were to do it, we would have to be careful not end up in a state of
# partial upgrades (remember to either do both --refresh (-y) and
# --sysupgrade (-u), or none of them, at least never just --refresh (-y)), and
# then there is also the potential issue with signing keys. These are exactly
# things that the arch-upgrade script is handling.
#
# Passes any script arguments to the pacman --sync command, so can execute
# script with name of additional packages as arguments, and with --noconfirm to
# run non-interactively proceeding without prompting user.
#
# NOTE: Assumes basic tools are already installed, including sudo.
# Run script ./arch-setup first to ensure this!
#

# Install packages using utility script arch-dev-base-cpp-install.
# It in turn uses utility script arch-dev-base-install, which installs base
# packages by default:
# - Diff command: diffutils
# - SSL toolkit (is also dependency of openssh, git and others): openssl
# - SSH client/server (used with git): openssh
# - Git client: git
# Then arch-dev-base-cpp-install supplies additional packages as arguments:
# - Boost headers and libraries (includes boost-libs which is a dependency of
#   gdb via source-highlight): boost
# - Ninja build-system: ninja
# - CMake build-system generator: cmake
# - GCC compiler: gcc
# - GDB debugger: gdb
# Here we supply additional packages to install as arguments.
"$(dirname "$0")/arch-dev-base-cpp-install" "$@" \
    `# Qt 5 (contains also dependencies of pyside2)` \
    qt5-base \
    qt5-charts \
    `# Python 3 (is also optional dependency of boost for python bindings)` \
    python \
    python-numpy \
    python-pylint \
    python-pytest \
    ipython \
    pyside2 \
    `# LevelDB headers and libraries (includes dependency snappy)` \
    leveldb
