#!/bin/sh
#
# Migrate an existing Claude Code installation for current user from a regular
# setup to a standalone setup.
#
# This can be when a standalone setup has accidentally been upgraded to a new
# version by the built-in updater, i.e. the auto-updater or a manual
# 'claude update' run, which would migrate it to a regular setup. This replaces
# the symbolic link ~/.local/bin/claude with the physical file it points to,
# and removes all remaining application executables in the version store.
#
# Also removes any remaining empty directory or subdirectories of the relevant
# base directories, assuming if they end up empty after the clean, it was
# Claude Code that created them.
#
# This script considers default locations known to be used by Claude, and also
# environment variables that Claude is known to check for custom locations.
# The defaults are all within the current user's home directory. For
# application files, Claude adheres to the XDG standard, considering base
# directory from environment variable XDG_DATA_HOME, falling back to
# ~/.local/share.
#

# If we could always assume that the distro is always set up with a non-root
# default user, then we could verify we are not running as root, since this
# considers a local Claude Code installation for the current user only!
#if [ ${EUID:-$(id -u)} -eq 0 ]; then
#    echo 'Please do not run this script as root' >&2
#    exit 1
#fi

# Resolve XDG conventional user binary directory.
# This is where the Claude executable is installed by default, and here we
# assume it was not manually installed elsewhere.
bin_dir="${HOME}/.local/bin"

# Resolve XDG standard data base directory, falling back to XDG default.
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"

if [ ! -L "${bin_dir}/claude" ]; then
    echo "The path '${bin_dir}/claude' is not a symbolic link so this already looks like a standalone setup" >&2
    exit 1
fi
mv "$(readlink -e "${bin_dir}/claude")" "${bin_dir}/claude" && rm --recursive --force "${data_home}/claude/versions" || { echo "Failed!" >&2; exit 1; }
find "${bin_dir}" -type d -empty -delete 2> /dev/null
find "${data_home}" -type d -empty -delete 2> /dev/null
rmdir "${HOME}/.local" 2> /dev/null # Remove parent if now empty (not XDG-governed)

unset bin_dir data_home
