#!/bin/sh

#
# Passes any script arguments to the apt-get install command,
# so can execute with --dry-run for instance.
#

#sudo apt-get update

# Possibly the following, but xz-utils and bzip2 are included as dependencies,
# and maybe not needing the otherones?
#    `# Basic tools (` \
#    xz-utils \
#    bzip2 \
#    unzip \
#    p7zip \

sudo apt-get install --no-install-recommends "$@" \
    `# SSL` \
    libssl-dev
    `# Git` \
    git \
    git-lfs \
    `# SSH client` \
    openssh-client \
    `# Qt 5` \
    qtbase5-dev \
    libqt5charts5-dev \
    `# Python 3` \
    python3 \
    python3-numpy \
    ipython3 \
    pylint3 \
    python3-pytest \
    pyside2-tools \
    `# G++` \
    g++ \
    `# Ninja` \
    ninja-build \
    `# CMake` \
    cmake \
    `# Boost: system,filesystem,date_time,serialization,thread,python (+ depedency libboost-dev containing headers)` \
    libboost-system-dev \
    libboost-filesystem-dev \
    libboost-date-time-dev \
    libboost-serialization-dev \
    libboost-thread-dev \
    libboost-python-dev \
    `# Armadillo` \
    libarmadillo-dev \
    `# Dlib` \
    libdlib-dev \
    libpng-dev \
    libsqlite3 \
    `# Doctest` \
    doctest-dev
