#!/bin/sh
#
# Fedora Linux in WSL basic configuration and installation of the basic tools.
#
# Intended to be executed immediately after a clean install, but can also be
# run later and repeated without creating trouble.
#
# Based on separate "sub-scripts" for each main action performed (documented
# below), which can also be executed separately.
#
# NOTE:
# - Written for WSL import of docker root filesystem of Fedora 33 and 34,
#   from Fedora Container Base image (with dnf) and Fedora Container Minimal
#   Base image (with microdnf).
# - Must be run by actual root user, not by use of sudo from regular user,
#   (sudo is not installed by default in the Fedora Container Minimal Base image).
# - Interactive! Will prompt user before doing any changes!
# - Skips installation of documentation, by specifying --nodocs as command line
#   argument. Standard base image has this configured as default with
#   "tsflags=nodocs" in /etc/dns/dns.conf, but this is not supported by microdnf
#   so for the minimal base image it must be added on command line.
#

# Verify running as root
if [ ${EUID:-$(id -u)} -ne 0 ]; then
    echo 'Please run this script as root'
    exit 1
fi

echo "Configuring locale..."
. "${0}-locale"

echo
echo "Configuring packages..."
. "${0}-packages"

# Note: bash-setup requires find command, which is installed by setup-packages!
echo
echo "Configuring bash shell environment"
. "$(dirname ${0})/bash-setup"

echo
echo Done
