#!/bin/sh
#
# Create convenience alias for running ssh-init script for current user.
#

"$(dirname "${0}")/bash-alias" "$@" \
    "ssh-init=. $(realpath "$(dirname "$0")/ssh-init")" \
    "si=ssh-init"
